package com.sure.pojo;

public class Auth {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.auth_id
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String authId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.auth_name
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String authName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.auth_entry
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String authEntry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.auth_type
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private Integer authType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.auth_order
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private Integer authOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.auth_parent
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String authParent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.auth_id
	 * @return  the value of sys_auth.auth_id
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getAuthId() {
		return authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.auth_id
	 * @param authId  the value for sys_auth.auth_id
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setAuthId(String authId) {
		this.authId = authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.auth_name
	 * @return  the value of sys_auth.auth_name
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getAuthName() {
		return authName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.auth_name
	 * @param authName  the value for sys_auth.auth_name
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setAuthName(String authName) {
		this.authName = authName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.auth_entry
	 * @return  the value of sys_auth.auth_entry
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getAuthEntry() {
		return authEntry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.auth_entry
	 * @param authEntry  the value for sys_auth.auth_entry
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setAuthEntry(String authEntry) {
		this.authEntry = authEntry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.auth_type
	 * @return  the value of sys_auth.auth_type
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public Integer getAuthType() {
		return authType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.auth_type
	 * @param authType  the value for sys_auth.auth_type
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setAuthType(Integer authType) {
		this.authType = authType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.auth_order
	 * @return  the value of sys_auth.auth_order
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public Integer getAuthOrder() {
		return authOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.auth_order
	 * @param authOrder  the value for sys_auth.auth_order
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setAuthOrder(Integer authOrder) {
		this.authOrder = authOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.auth_parent
	 * @return  the value of sys_auth.auth_parent
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getAuthParent() {
		return authParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.auth_parent
	 * @param authParent  the value for sys_auth.auth_parent
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setAuthParent(String authParent) {
		this.authParent = authParent;
	}
}