package com.sure.pojo;

public class RoleAuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.role_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.auth_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    private String authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.role_id
     *
     * @return the value of sys_role_auth.role_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.role_id
     *
     * @param roleId the value for sys_role_auth.role_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.auth_id
     *
     * @return the value of sys_role_auth.auth_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.auth_id
     *
     * @param authId the value for sys_role_auth.auth_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }
}