package com.sure.pojo;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_name
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_password
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String userPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.is_locked
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private Boolean isLocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.expiration_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private Date expirationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.update_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.edit_by
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String editBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.remark
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_name
	 * @return  the value of sys_user.user_name
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_name
	 * @param userName  the value for sys_user.user_name
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_password
	 * @return  the value of sys_user.user_password
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_password
	 * @param userPassword  the value for sys_user.user_password
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.is_locked
	 * @return  the value of sys_user.is_locked
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public Boolean getIsLocked() {
		return isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.is_locked
	 * @param isLocked  the value for sys_user.is_locked
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.expiration_date
	 * @return  the value of sys_user.expiration_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public Date getExpirationDate() {
		return expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.expiration_date
	 * @param expirationDate  the value for sys_user.expiration_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_date
	 * @return  the value of sys_user.create_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_date
	 * @param createDate  the value for sys_user.create_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.update_date
	 * @return  the value of sys_user.update_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.update_date
	 * @param updateDate  the value for sys_user.update_date
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.edit_by
	 * @return  the value of sys_user.edit_by
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getEditBy() {
		return editBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.edit_by
	 * @param editBy  the value for sys_user.edit_by
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setEditBy(String editBy) {
		this.editBy = editBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.remark
	 * @return  the value of sys_user.remark
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.remark
	 * @param remark  the value for sys_user.remark
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}