package com.sure.pojo;

public class UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_name
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.user_name
     *
     * @return the value of sys_user_role.user_name
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.user_name
     *
     * @param userName the value for sys_user_role.user_name
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.role_id
     *
     * @return the value of sys_user_role.role_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.role_id
     *
     * @param roleId the value for sys_user_role.role_id
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}