package com.sure.dao;

import java.util.List;

import com.sure.pojo.Auth;

public interface AuthMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	int deleteByPrimaryKey(String authId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	int insert(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	int insertSelective(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	Auth selectByPrimaryKey(String authId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	int updateByPrimaryKeySelective(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Thu Jun 30 17:59:14 CST 2016
	 */
	int updateByPrimaryKey(Auth record);

	/**
     * 获取�?��权限的列�?
     * @return
     */
    List<Auth> findAuths();
    
    /**
     * 获取用户的权限列�?
     * @param userName
     * @return
     */
    List<Auth> findUserAuthsByUserName(String userName);
}