package com.sure.dao;

import java.util.List;
import java.util.Map;

import com.sure.pojo.Auth;

public interface AuthMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Wed Jul 20 14:37:32 CST 2016
	 */
	int deleteByPrimaryKey(String authId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Wed Jul 20 14:37:32 CST 2016
	 */
	int insert(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Wed Jul 20 14:37:32 CST 2016
	 */
	int insertSelective(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Wed Jul 20 14:37:32 CST 2016
	 */
	Auth selectByPrimaryKey(String authId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Wed Jul 20 14:37:32 CST 2016
	 */
	int updateByPrimaryKeySelective(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbggenerated  Wed Jul 20 14:37:32 CST 2016
	 */
	int updateByPrimaryKey(Auth record);

	/**
	 * 获取权限的列表  
	 * @param param
	 * @return
	 */
    List<Auth> findAuths(Map param);
    
    /**
     * 获取用户的权限列表     
     * @param userName
     * @return
     */
    List<Auth> findUserAuthsByUserName(String userName);
}