package com.sure.dao;

import java.util.List;

import com.sure.pojo.RoleAuthKey;

public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    int deleteByPrimaryKey(RoleAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    int insert(RoleAuthKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    int insertSelective(RoleAuthKey record);
    
    List<String> findAuthIdsByRoleId(int roleId);
    
    int deleteByRoleId(int roleId);
    
    int deleteByAuthId(String authId);
}