package com.sure.dao;

import java.util.List;

import com.sure.pojo.UserRoleKey;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    int deleteByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    int insert(UserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jul 20 14:37:32 CST 2016
     */
    int insertSelective(UserRoleKey record);
    
    List<Integer> findRoleIdsByUserName(String userName);
    
    int deleteByUserName(String userName);
    
    int deleteByRoleId(int roleId);
}